version: '3.1'
services:
  app:
    image: django_article
    container_name: django_article
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
